on: [push]
name: build
jobs:
  build:
    name: Build for Windows
    runs-on: windows-2019 # or macOS-latest, or windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: haskell/actions/setup@v1
        with:
          ghc-version: '8.8.3'
          enable-stack: true
          stack-version: 'latest'
      - name: Install Dependencies
        shell: powershell
        run: |
          Invoke-WebRequest -Uri "https://www.libsdl.org/release/SDL2-devel-2.0.10-VC.zip" -OutFile "SDL2-devel-2.0.10-VC.zip"
          Expand-Archive -Path SDL2-devel-2.0.10-VC.zip
          echo "SDL2_DIR=$(pwd)\SDL2-devel-2.0.10-VC\SDL2-2.0.10\" >>${env:GITHUB_ENV}
          Invoke-WebRequest -Uri "https://github.com/ocornut/imgui/files/3789205/vulkan-sdk-1.1.121.2.zip" -OutFile vulkan-sdk-1.1.121.2.zip
          Expand-Archive -Path vulkan-sdk-1.1.121.2.zip
          echo "VULKAN_SDK=$(pwd)\vulkan-sdk-1.1.121.2\" >>${env:GITHUB_ENV}
      - name: Build
        run: stack build --copy-bins --local-bin-path .
      - name: Upload binary
        uses: actions/upload-artifact@v2
        with:
          name: windows-bin
          path: network-hw-exe.exe
